#!/bin/bash

# functions

function pause(){
  read -p "$*"
}

function welcome(){
  echo -e "Welcome to installer of einDa skin to DA"
}

function bar(){
  echo "========================================"
}

function end(){
  bar
  echo "Congratulations, new skin was installed"
  echo "Now go to http://yourdomain:2222 and"
  echo "1. Join admin account"
  echo "2. Join to skin section"
  echo "3. Select einDa-skin and apply to me"
  bar
  echo "Thanks for using einDa skin"
  bar
}

function join-folder(){
  cd /usr/local/directadmin/data/skins/
}

function install(){
  echo "installing..."
  git clone https://github.com/smicroz/einDa-skin.git
  chown -R diradmin:diradmin einDa-skin/
}

# innit

bar
welcome
bar

join-folder

directory=einDa-skin

if [ -d "$directory" ]; then
  echo "The directory einDa-skin already exists"
  echo "If you want install skin, the installer will remove folder."
  pause 'If you agree, press [Enter] key for continue...'
  rm -rf $directory/
  install
else
  pause 'Press [Enter] key for start installation...'
  install
fi

end